export const brands = [
    {src: "/images/brands/advance.webp",alt: "Advance"},
    {src: "/images/brands/afford.webp",alt: "Afford"},
    {src: "/images/brands/blondi.webp",alt: "Blondi"},
    {src: "/images/brands/boehringer.svg",alt: "Boehringer Ingelheim"},
    {src: "/images/brands/holliday.png",alt: "Holliday"},
    {src: "/images/brands/janvier.svg",alt: "janvier"},
    {src: "/images/brands/jhonMartin.svg",alt: "Jhon Martin"},
    {src: "/images/brands/konig.png",alt: "Konig"},
    {src: "/images/brands/kualcos.png",alt: "Kualcos"},
    {src: "/images/brands/labyes.svg",alt: "Labyes"},
    {src: "/images/brands/livra.jpg",alt: "Livra"},
    {src: "/images/brands/msd.png",alt: "MSD"},
    {src: "/images/brands/namhut.png",alt: "Namhut"},
    {src: "/images/brands/osspret.png",alt: "Osspret"},
    {src: "/images/brands/professionalvet.png",alt: "Professional Vet"},
    {src: "/images/brands/purina.webp",alt: "Purina"},
    {src: "/images/brands/richmond.png",alt: "Richmond"},
    {src: "/images/brands/royal.webp",alt: "Royal Canin"},
    {src: "/images/brands/ruminal.png",alt: "Ruminal"},
    {src: "/images/brands/vetanco.png",alt: "Vetanco"},
    {src: "/images/brands/zoetis.svg",alt: "Zeotis"},
]
